Repository Team-2Win0Lose/Front-Kick, pull requests merged in 2023-10, with the labels that each got.

#125 Fix: change tsconfig.json
  .gitignore
  dist/assets/teams/강원FC 2.png
  src/components/CreateRoom/Step/Step.tsx
  src/components/Filter/MultiFilter.tsx
  src/components/Headerbar/Account.tsx
  src/components/Headerbar/Menu/CheeringTeam.tsx
  src/components/Headerbar/Menu/Sidebar.tsx
  src/feature/fetchSlice.ts
  src/pages/CreateRoom/CreateRoom.tsx
  tsconfig.json
Labels: fix

#127 Feat: cardList 수정 및 필터 수정
  src/components/CreateRoom/Step/MatchDate/TeamDateSelectCarousel.tsx
  src/components/Filter/MultiFilter.tsx
  src/components/FindAccompany/AccompanyList.tsx
  src/components/MyAccompany/AccompanyBox.tsx
  src/lib/interface.ts
  src/pages/FindAccompany.tsx
  src/pages/FindAccompanyDetail.tsx
  src/util/calculateDday.ts
  src/util/sliceTitle.ts
  src/util/teamnameConvertImg.ts
Labels: feat

#146 Fix: fix function
  src/pages/FindAccompanyDetail.tsx
  src/util/compareDate.ts
Labels: feat, fix

#147 Fix: 반응형
  public/assets/banner1.png
  public/assets/banner2.png
  public/assets/banner3.png
  public/assets/banner4.png
  src/components/Banner/BannerCarousel.tsx
  src/components/CreateRoom/Step/MatchDate/MatchingInfo.tsx
  src/components/CreateRoom/Step/MatchDate/TeamDateCalendar.tsx
  src/components/CreateRoom/Step/MatchDate/TeamDateSelectCarousel.tsx
  src/components/CreateRoom/Step/Step.tsx
  src/components/Headerbar/Account.tsx
  src/components/Headerbar/Menu/Sidebar.tsx
  src/components/Layouts/Header.tsx
  src/components/TeamRating/TeamCardCarousel.tsx
Labels: fix

#148 Feat: 게시글 신청 구현
  src/components/CreateRoom/Step/SelectCard/PlaceCard.tsx
  src/components/Headerbar/Menu/CheeringTeam.tsx
  src/components/Headerbar/Menu/Sidebar.tsx
  src/components/MyAccompany/AccompanyBox.tsx
  src/lib/interface.ts
  src/pages/FindAccompanyDetail.tsx
  src/util/compareDate.ts
  src/util/teamnameConvertImg.ts
Labels: feat

#151 Fix: merge
  src/components/CreateRoom/Step/MatchDate/TeamDateSelectCarousel.tsx
  src/components/Filter/MultiFilter.tsx
  src/components/OnboardingTeamSelect/OnboardingTeamSelect.tsx
  src/components/TeamRating/TeamCardCarousel.tsx
  src/pages/main.tsx
  src/util/GlobalStyle.tsx
Labels: fix

#154 Fix: 반응형
  src/components/CreateRoom/Step/MatchDate/MatchingInfo.tsx
  src/components/CreateRoom/Step/MatchDate/TeamDateCalendar.tsx
  src/components/CreateRoom/Step/MatchDate/TeamDateSelectCarousel.tsx
  src/components/CreateRoom/Step/MeetingPlace/MapContainer.tsx
  src/components/CreateRoom/Step/MeetingPlace/PlaceSearch.tsx
  src/components/CreateRoom/Step/Step.tsx
  src/components/Modal/AttractionSearchModal.tsx
  src/components/Modal/FoodSearchModal.tsx
  src/components/Modal/HouseSearchModal.tsx
Labels: fix

#157 Fix: 반응형 수정
  src/components/CreateRoom/Step/Detailinfo/ContentInput.tsx
  src/components/CreateRoom/Step/Detailinfo/Detailinfo_2.tsx
  src/components/CreateRoom/Step/Detailinfo/MinMaxCnt.tsx
  src/components/CreateRoom/Step/Detailinfo/TitleName.tsx
  src/components/CreateRoom/Step/Summary/Summary.tsx
  src/components/HashTag/FilterBox.tsx
  src/components/Headerbar/Menu/Sidebar.tsx
  src/components/Layouts/Layout.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/LoginHeader.tsx
  src/components/MyAccompany/AccompanyBox.tsx
  src/components/OnboardingTeamSelect/OnboardingTeamSelect.tsx
  src/components/OnboardingTeamSelect/SelectTeamCard.tsx
  src/components/TeamRating/TeamCardCarousel.tsx
  src/pages/FindAccompany.tsx
  src/pages/Login/Login.tsx
  src/pages/MyAccompany/MyAccompany.tsx
  src/pages/main.tsx
Labels: fix

#160 Fix: merge
  src/pages/main.tsx
Labels: fix

#161 Fix: 각종 수정
  src/components/CreateRoom/Step/MatchDate/MatchingInfo.tsx
  src/components/CreateRoom/Step/MeetingPlace/MapContainer.tsx
  src/components/CreateRoom/Step/Step.tsx
  src/pages/main.tsx
Labels: fix

#164 Fix: 동행만들기 1단계 선택
  src/components/CreateRoom/Step/Detailinfo/MinMaxCnt.tsx
  src/components/CreateRoom/Step/MatchDate/MatchingInfo.tsx
  src/components/Headerbar/Navbar/Navbar.tsx
  src/components/Layouts/Header.tsx
  src/components/Layouts/Layout.tsx
Labels: fix

#168 Fix: merge
  src/components/Modal/AttractionSearchModal.tsx
  src/components/Modal/FoodSearchModal.tsx
  src/components/Modal/HouseSearchModal.tsx
  src/components/Signup/SignupForm.tsx
Labels: fix

#181 Fix: 마크업 수정
  src/components/CreateRoom/Step/MatchDate/MatchingInfo.tsx
  src/components/CreateRoom/Step/MatchDate/TeamDateCalendar.tsx
  src/components/CreateRoom/Step/MeetingPlace/MapContainer.tsx
  src/components/Headerbar/Menu/CheeringTeam.tsx
  src/components/Headerbar/Menu/Sidebar.tsx
  src/components/Modal/AttractionSearchModal.tsx
  src/components/Modal/FoodSearchModal.tsx
  src/components/Modal/HouseSearchModal.tsx
  src/components/MyAccompany/AccompanyBox.tsx
  src/pages/FindAccompanyDetail.tsx
Labels: fix
